kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
  namespace: jeff-tls
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: server
          secret:
            secretName: server
        - name: truststore
          secret:
            secretName: truststore
      containers:
        - name: server
          image: 'image-registry.openshift-image-registry.svc:5000/jeff-tls/server:latest'
          ports:
            - containerPort: 8443
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: server
              readOnly: true
              mountPath: /deployments/tls
            - name: truststore
              readOnly: true
              mountPath: /deployments/tls/ca
